language: php

php:
    - '7.4'
    - '8.0'

before_install:
  - phpenv config-add tests/travis/php$TRAVIS_PHP_VERSION.ini

install:
  - export TRAVIS_PHP_VERSION; sh tests/travis/install-script.sh

script:
  - sh tests/travis/run-test.sh
