name: tests

on: 
  push:
      branches:
          - master

jobs:
  no_ext_tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: PHP8.1
            os: ubuntu-latest
            php: '8.1'
            phpunit: '10.5'
          - name: PHP8.3
            os: ubuntu-latest
            php: '8.3'
            phpunit: '11.5'
          - name: PHP8.4
            os: ubuntu-latest
            php: '8.4'
            phpunit: '11.5'
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v4"

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: PHP Static Analysys
        uses: php-actions/phpstan@v3
        with:
          php_version: ${{ matrix.php }}
          path: src/

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit.xml
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
          php_extensions: pdo_sqlite gd
        env:
          PLOT_RENDERER_SKIP: true
